#include <pb_decode.h>
#include <pb_encode.h>
#include <string.h>

#include <poison_session.pb.h>

#include "../../../../services/rpc/rpc_poison_session.h"

#include "../test.h"

MU_TEST(poison_session_envelope_round_trip) {
    PB_Poison_SessionEnvelope original = PB_Poison_SessionEnvelope_init_zero;
    original.protocol_version = 2;
    original.session_id = 0x0102030405060708ULL;
    original.sequence = 9;
    original.acknowledgement = 8;
    strcpy(original.channel, "device");
    original.payload.size = 4;
    original.payload.bytes[0] = 0x10;
    original.payload.bytes[1] = 0x20;
    original.payload.bytes[2] = 0x30;
    original.payload.bytes[3] = 0x40;
    original.authentication_tag.size = 16;
    for(size_t index = 0; index < original.authentication_tag.size; ++index) {
        original.authentication_tag.bytes[index] = (uint8_t)index;
    }

    uint8_t encoded[1024] = {0};
    pb_ostream_t output = pb_ostream_from_buffer(encoded, sizeof(encoded));
    mu_check(pb_encode(&output, PB_Poison_SessionEnvelope_fields, &original));
    mu_check(output.bytes_written > 0);
    mu_check(output.bytes_written <= sizeof(encoded));

    PB_Poison_SessionEnvelope decoded = PB_Poison_SessionEnvelope_init_zero;
    pb_istream_t input = pb_istream_from_buffer(encoded, output.bytes_written);
    mu_check(pb_decode(&input, PB_Poison_SessionEnvelope_fields, &decoded));
    mu_check(decoded.protocol_version == original.protocol_version);
    mu_check(decoded.session_id == original.session_id);
    mu_check(decoded.sequence == original.sequence);
    mu_check(decoded.acknowledgement == original.acknowledgement);
    mu_check(strcmp(decoded.channel, original.channel) == 0);
    mu_check(decoded.payload.size == original.payload.size);
    mu_check(memcmp(decoded.payload.bytes, original.payload.bytes, original.payload.size) == 0);
    mu_check(decoded.authentication_tag.size == original.authentication_tag.size);
}

MU_TEST(poison_session_bounds_reject_truncated_output) {
    PB_Poison_SessionEnvelope envelope = PB_Poison_SessionEnvelope_init_zero;
    envelope.protocol_version = 2;
    envelope.payload.size = sizeof(envelope.payload.bytes);
    for(size_t index = 0; index < envelope.payload.size; ++index) {
        envelope.payload.bytes[index] = 0xAA;
    }
    uint8_t encoded[1024] = {0};
    pb_ostream_t output = pb_ostream_from_buffer(encoded, sizeof(encoded));
    mu_check(pb_encode(&output, PB_Poison_SessionEnvelope_fields, &envelope));
    mu_check(output.bytes_written <= sizeof(encoded));

    output = pb_ostream_from_buffer(encoded, 16);
    mu_check(!pb_encode(&output, PB_Poison_SessionEnvelope_fields, &envelope));
}

MU_TEST(poison_session_authentication_rejects_tampering_and_replay) {
    PoisonSession session;
    uint8_t key[POISON_SESSION_KEY_BYTES];
    for(size_t index = 0; index < sizeof(key); ++index)
        key[index] = (uint8_t)(index + 1u);
    poison_session_init(&session);
    mu_check(poison_session_begin_negotiation(&session, 2u) == PoisonSessionResultOk);
    mu_check(poison_session_begin_confirmation(&session, 77u) == PoisonSessionResultOk);
    mu_check(poison_session_set_authentication_key(&session, key) == PoisonSessionResultOk);
    mu_check(poison_session_confirm(&session, true) == PoisonSessionResultOk);
    mu_check(poison_session_activate(&session) == PoisonSessionResultOk);

    uint8_t payload[] = {0x10, 0x20};
    uint8_t tag[POISON_SESSION_AUTH_TAG_BYTES] = {0};
    /* The tag is generated by a second session with the same negotiated key and ID. */
    PoisonSession sender;
    poison_session_init(&sender);
    mu_check(poison_session_begin_negotiation(&sender, 2u) == PoisonSessionResultOk);
    mu_check(poison_session_begin_confirmation(&sender, 77u) == PoisonSessionResultOk);
    mu_check(poison_session_set_authentication_key(&sender, key) == PoisonSessionResultOk);
    mu_check(poison_session_confirm(&sender, true) == PoisonSessionResultOk);
    mu_check(poison_session_activate(&sender) == PoisonSessionResultOk);
    mu_check(
        poison_session_sign_frame(&sender, 2u, 0u, 0u, "workload", payload, sizeof(payload), tag) ==
        PoisonSessionResultOk);
    mu_check(
        poison_session_authenticate_rx(
            &session, 2u, 0u, 0u, "workload", payload, sizeof(payload), tag) ==
        PoisonSessionResultOk);
    mu_check(
        poison_session_authenticate_rx(
            &session, 2u, 0u, 0u, "workload", payload, sizeof(payload), tag) ==
        PoisonSessionResultReplay);
    payload[0] ^= 0x01u;
    mu_check(
        poison_session_authenticate_rx(
            &session, 2u, 1u, 0u, "workload", payload, sizeof(payload), tag) ==
        PoisonSessionResultInvalid);
}

MU_TEST(poison_session_encrypts_directional_frames_and_rejects_tampering) {
    PoisonSession sender;
    PoisonSession receiver;
    uint8_t client_to_device[POISON_SESSION_KEY_BYTES];
    uint8_t device_to_client[POISON_SESSION_KEY_BYTES];
    for(size_t index = 0; index < POISON_SESSION_KEY_BYTES; ++index) {
        client_to_device[index] = (uint8_t)(index + 1u);
        device_to_client[index] = (uint8_t)(0x80u + index);
    }
    poison_session_init(&sender);
    poison_session_init(&receiver);
    mu_check(poison_session_begin_negotiation(&sender, 2u) == PoisonSessionResultOk);
    mu_check(poison_session_begin_confirmation(&sender, 91u) == PoisonSessionResultOk);
    mu_check(poison_session_confirm(&sender, true) == PoisonSessionResultOk);
    mu_check(poison_session_begin_negotiation(&receiver, 2u) == PoisonSessionResultOk);
    mu_check(poison_session_begin_confirmation(&receiver, 91u) == PoisonSessionResultOk);
    mu_check(poison_session_confirm(&receiver, true) == PoisonSessionResultOk);
    mu_check(
        poison_session_set_directional_keys(&sender, device_to_client, client_to_device) ==
        PoisonSessionResultOk);
    mu_check(
        poison_session_set_directional_keys(&receiver, client_to_device, device_to_client) ==
        PoisonSessionResultOk);
    mu_check(poison_session_activate(&sender) == PoisonSessionResultOk);
    mu_check(poison_session_activate(&receiver) == PoisonSessionResultOk);

    const uint8_t plaintext[] = {0x10u, 0x20u, 0x30u, 0x40u};
    uint8_t ciphertext[sizeof(plaintext)] = {0};
    uint8_t decoded[sizeof(plaintext)] = {0};
    uint8_t tag[POISON_SESSION_AUTH_TAG_BYTES] = {0};
    uint64_t sequence = UINT64_MAX;
    mu_check(
        poison_session_encrypt_tx(
            &sender, 0u, "rpc", plaintext, sizeof(plaintext), &sequence, ciphertext, tag) ==
        PoisonSessionResultOk);
    mu_check(sequence == 0u);
    mu_check(memcmp(ciphertext, plaintext, sizeof(plaintext)) != 0);
    mu_check(
        poison_session_decrypt_rx(
            &receiver, sequence, 0u, "rpc", ciphertext, sizeof(ciphertext), tag, decoded) ==
        PoisonSessionResultOk);
    mu_check(memcmp(decoded, plaintext, sizeof(plaintext)) == 0);
    mu_check(
        poison_session_decrypt_rx(
            &receiver, sequence, 0u, "rpc", ciphertext, sizeof(ciphertext), tag, decoded) ==
        PoisonSessionResultReplay);

    uint8_t tampered_tag[POISON_SESSION_AUTH_TAG_BYTES];
    memcpy(tampered_tag, tag, sizeof(tampered_tag));
    tampered_tag[0] ^= 1u;
    mu_check(
        poison_session_decrypt_rx(
            &receiver, 1u, 0u, "rpc", ciphertext, sizeof(ciphertext), tampered_tag, decoded) ==
        PoisonSessionResultInvalid);
    mu_check(receiver.next_rx_sequence == 1u);
}

MU_TEST(poison_pairing_derives_keys_only_after_exact_device_confirmation) {
    uint8_t client_private[POISON_CRYPTO_P256_PRIVATE_BYTES];
    uint8_t client_public[POISON_CRYPTO_P256_PUBLIC_BYTES];
    uint8_t identity_private[POISON_CRYPTO_P256_PRIVATE_BYTES];
    uint8_t identity_public[POISON_CRYPTO_P256_PUBLIC_BYTES];
    mu_check(
        poison_crypto_generate_p256_keypair(client_private, client_public) ==
        PoisonCryptoResultOk);
    mu_check(
        poison_crypto_generate_p256_keypair(identity_private, identity_public) ==
        PoisonCryptoResultOk);

    PB_Poison_PairingHello hello = PB_Poison_PairingHello_init_zero;
    hello.protocol_version = 2u;
    hello.client_ephemeral_public_key.size = sizeof(client_public);
    memcpy(hello.client_ephemeral_public_key.bytes, client_public, sizeof(client_public));
    hello.client_identity_public_key.size = sizeof(identity_public);
    memcpy(hello.client_identity_public_key.bytes, identity_public, sizeof(identity_public));
    strcpy(hello.client_name, "field-console");
    hello.requested_role = PoisonRoleOperator;
    hello.requested_capabilities = POISON_CAPABILITY_STATUS | POISON_CAPABILITY_CONTROL;
    hello.client_nonce.size = 32u;
    for(size_t index = 0; index < hello.client_nonce.size; ++index)
        hello.client_nonce.bytes[index] = (uint8_t)(0x40u + index);

    PoisonPairingHandshake handshake;
    PB_Poison_PairingChallenge challenge = PB_Poison_PairingChallenge_init_zero;
    mu_check(poison_pairing_begin(&handshake, &hello, 1000u, &challenge));
    mu_check(challenge.protocol_version == 2u);
    mu_check(challenge.session_id != 0u);
    mu_check(challenge.device_ephemeral_public_key.size == POISON_CRYPTO_P256_PUBLIC_BYTES);
    mu_check(challenge.device_nonce.size == 32u);
    mu_check(challenge.transcript_digest.size == POISON_CRYPTO_SHA256_BYTES);
    mu_check(strlen(challenge.confirmation_code) == 6u);

    PB_Poison_PairingConfirm confirm = PB_Poison_PairingConfirm_init_zero;
    confirm.transcript_digest.size = challenge.transcript_digest.size;
    memcpy(
        confirm.transcript_digest.bytes,
        challenge.transcript_digest.bytes,
        challenge.transcript_digest.size);
    strcpy(confirm.confirmation_code, challenge.confirmation_code);
    confirm.physical_confirmation = true;
    size_t identity_signature_size = 0u;
    mu_check(
        poison_crypto_sign_p256_sha256(
            identity_private,
            challenge.transcript_digest.bytes,
            confirm.client_identity_signature.bytes,
            &identity_signature_size) == PoisonCryptoResultOk);
    confirm.client_identity_signature.size = identity_signature_size;
    mu_check(!poison_pairing_complete(&handshake, &confirm, 1001u, false));
    mu_check(handshake.session.state != PoisonSessionActive);

    mu_check(poison_pairing_begin(&handshake, &hello, 2000u, &challenge));
    confirm.transcript_digest.size = challenge.transcript_digest.size;
    memcpy(
        confirm.transcript_digest.bytes,
        challenge.transcript_digest.bytes,
        challenge.transcript_digest.size);
    strcpy(confirm.confirmation_code, challenge.confirmation_code);
    identity_signature_size = 0u;
    mu_check(
        poison_crypto_sign_p256_sha256(
            identity_private,
            challenge.transcript_digest.bytes,
            confirm.client_identity_signature.bytes,
            &identity_signature_size) == PoisonCryptoResultOk);
    confirm.client_identity_signature.size = identity_signature_size;
    mu_check(poison_pairing_complete(&handshake, &confirm, 2001u, true));
    mu_check(handshake.session.state == PoisonSessionActive);
    mu_check(handshake.session.directional_keys_set);
    mu_check(
        memcmp(
            handshake.session.client_identity_digest,
            handshake.client_identity_digest,
            sizeof(handshake.client_identity_digest)) == 0);

    confirm.transcript_digest.bytes[0] ^= 1u;
    mu_check(!poison_pairing_complete(&handshake, &confirm, 2002u, true));

    mu_check(poison_pairing_begin(&handshake, &hello, 3000u, &challenge));
    confirm.transcript_digest.size = challenge.transcript_digest.size;
    memcpy(
        confirm.transcript_digest.bytes,
        challenge.transcript_digest.bytes,
        challenge.transcript_digest.size);
    strcpy(confirm.confirmation_code, challenge.confirmation_code);
    identity_signature_size = 0u;
    mu_check(
        poison_crypto_sign_p256_sha256(
            client_private,
            challenge.transcript_digest.bytes,
            confirm.client_identity_signature.bytes,
            &identity_signature_size) == PoisonCryptoResultOk);
    confirm.client_identity_signature.size = identity_signature_size;
    mu_check(!poison_pairing_complete(&handshake, &confirm, 3001u, true));
    mu_check(handshake.session.state == PoisonSessionRevoked);
}

MU_TEST(poison_session_resume_token_is_one_use_sequence_bound_and_revocable) {
    PoisonSession session;
    poison_session_init(&session);
    session.state = PoisonSessionActive;
    session.protocol_version = 2u;
    session.session_id = 0x1122334455667788ULL;
    session.next_tx_sequence = 7u;
    session.next_rx_sequence = 5u;
    session.directional_keys_set = true;
    memset(session.receive_key, 0x31, sizeof(session.receive_key));
    memset(session.transmit_key, 0x72, sizeof(session.transmit_key));

    uint8_t token[POISON_SESSION_RESUME_TOKEN_BYTES];
    memset(token, 0xA5, sizeof(token));
    PoisonSessionResumeSlot slot;
    poison_session_resume_slot_init(&slot);
    mu_check(poison_session_resume_store(&slot, &session, token, 1000u, 500u));
    mu_check(slot.active);
    mu_check(memcmp(slot.token_digest, token, sizeof(token)) != 0);

    PoisonSession resumed;
    uint8_t wrong_token[POISON_SESSION_RESUME_TOKEN_BYTES];
    memcpy(wrong_token, token, sizeof(wrong_token));
    wrong_token[0] ^= 1u;
    mu_check(
        !poison_session_resume_take(&slot, session.session_id, wrong_token, 6u, 1100u, &resumed));
    mu_check(slot.active);
    mu_check(!poison_session_resume_take(&slot, session.session_id, token, 5u, 1100u, &resumed));
    mu_check(slot.active);
    mu_check(poison_session_resume_take(&slot, session.session_id, token, 6u, 1100u, &resumed));
    mu_check(!slot.active);
    mu_check(resumed.state == PoisonSessionActive);
    mu_check(resumed.session_id == session.session_id);
    mu_check(resumed.next_tx_sequence == session.next_tx_sequence);
    mu_check(resumed.next_rx_sequence == session.next_rx_sequence);
    mu_check(memcmp(resumed.receive_key, session.receive_key, sizeof(session.receive_key)) == 0);

    mu_check(poison_session_resume_store(&slot, &session, token, 2000u, 500u));
    mu_check(!poison_session_resume_take(&slot, session.session_id, token, 6u, 2500u, &resumed));
    mu_check(!slot.active);

    mu_check(poison_session_resume_store(&slot, &session, token, 3000u, 500u));
    poison_session_resume_revoke(&slot);
    mu_check(!slot.active);
    mu_check(!poison_session_resume_take(&slot, session.session_id, token, 6u, 3001u, &resumed));
}

MU_TEST_SUITE(poison_session_suite) {
    MU_RUN_TEST(poison_session_envelope_round_trip);
    MU_RUN_TEST(poison_session_bounds_reject_truncated_output);
    MU_RUN_TEST(poison_session_authentication_rejects_tampering_and_replay);
    MU_RUN_TEST(poison_session_encrypts_directional_frames_and_rejects_tampering);
    MU_RUN_TEST(poison_pairing_derives_keys_only_after_exact_device_confirmation);
    MU_RUN_TEST(poison_session_resume_token_is_one_use_sequence_bound_and_revocable);
}

void poison_session_run_tests(void) {
    MU_RUN_SUITE(poison_session_suite);
}
