#!/usr/bin/env python3

import argparse
import json
from pathlib import Path

import heatshrink2


MAGIC = b"PMR1"
CAPABILITIES = {"observe": 0, "control": 1, "active": 2, "admin": 3}
FIELDS = {
    "id",
    "label",
    "command",
    "capability",
    "argumentRequired",
    "producesCapture",
}


def validate_commands(commands):
    if not isinstance(commands, list) or not commands:
        raise ValueError("registry must be a non-empty list")
    seen = set()
    for command in commands:
        if not isinstance(command, dict) or set(command) != FIELDS:
            raise ValueError("every command must use the exact registry schema")
        if command["capability"] not in CAPABILITIES:
            raise ValueError(f"invalid capability for {command.get('id', '<unknown>')}")
        if not isinstance(command["argumentRequired"], bool) or not isinstance(
            command["producesCapture"], bool
        ):
            raise ValueError("command flags must be booleans")
        for field in ("id", "label", "command"):
            value = command[field]
            if not isinstance(value, str) or not value or "\x00" in value:
                raise ValueError(f"invalid {field}")
            encoded = value.encode("utf-8")
            if len(encoded) > 255:
                raise ValueError(f"{field} exceeds the one-byte registry bound")
        if command["id"] in seen:
            raise ValueError(f"duplicate command id: {command['id']}")
        seen.add(command["id"])
        has_argument = "{arg}" in command["command"]
        if has_argument != command["argumentRequired"]:
            raise ValueError(f"argument metadata mismatch for {command['id']}")


def serialize_registry(commands):
    validate_commands(commands)
    if len(commands) > 65535:
        raise ValueError("registry command count exceeds uint16")
    output = bytearray(MAGIC)
    output.extend(len(commands).to_bytes(2, "little"))
    for command in commands:
        flags = int(command["argumentRequired"]) | (
            int(command["producesCapture"]) << 1
        )
        output.extend((CAPABILITIES[command["capability"]], flags))
        for field in ("id", "label", "command"):
            value = command[field].encode("utf-8")
            output.append(len(value))
            output.extend(value)
            output.append(0)
    return bytes(output)


def encode_registry(commands):
    compressed = heatshrink2.compress(
        serialize_registry(commands), window_sz2=8, lookahead_sz2=4
    )
    if len(compressed) > 65535:
        raise ValueError("compressed registry exceeds uint16")
    return b"\x01\x00" + len(compressed).to_bytes(2, "little") + compressed


def decode_registry(encoded):
    if len(encoded) < 4 or encoded[0] != 1 or encoded[1] != 0:
        raise ValueError("invalid compression header")
    compressed_size = int.from_bytes(encoded[2:4], "little")
    if len(encoded) != compressed_size + 4:
        raise ValueError("compressed registry length mismatch")
    raw = heatshrink2.decompress(encoded[4:], window_sz2=8, lookahead_sz2=4)
    if len(raw) < 6 or raw[:4] != MAGIC:
        raise ValueError("invalid registry magic")
    count = int.from_bytes(raw[4:6], "little")
    capabilities = tuple(CAPABILITIES)
    commands = []
    offset = 6
    for _ in range(count):
        if offset + 2 > len(raw):
            raise ValueError("truncated registry metadata")
        capability, flags = raw[offset : offset + 2]
        offset += 2
        if capability >= len(capabilities) or flags & ~0x03:
            raise ValueError("invalid registry metadata")
        values = []
        for _field in range(3):
            if offset >= len(raw):
                raise ValueError("truncated registry string length")
            length = raw[offset]
            offset += 1
            if not length or offset + length >= len(raw):
                raise ValueError("truncated registry string")
            values.append(raw[offset : offset + length].decode("utf-8"))
            offset += length
            if raw[offset] != 0:
                raise ValueError("registry string is not terminated")
            offset += 1
        commands.append(
            {
                "id": values[0],
                "label": values[1],
                "command": values[2],
                "capability": capabilities[capability],
                "argumentRequired": bool(flags & 0x01),
                "producesCapture": bool(flags & 0x02),
            }
        )
    if offset != len(raw):
        raise ValueError("registry has trailing bytes")
    validate_commands(commands)
    return commands


def render_registry_include(commands):
    raw = serialize_registry(commands)
    encoded = encode_registry(commands)
    lines = [
        "/* Generated by scripts/marauder_registry.py; do not edit manually. */",
        f"#define ESP32_MARAUDER_REGISTRY_COUNT ({len(commands)}u)",
        f"#define ESP32_MARAUDER_REGISTRY_DECODED_SIZE ({len(raw)}u)",
        "static const uint8_t esp32_marauder_registry_encoded[] = {",
    ]
    for offset in range(0, len(encoded), 12):
        chunk = encoded[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend(("};", ""))
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("registry", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    commands = json.loads(args.registry.read_text(encoding="utf-8"))
    rendered = render_registry_include(commands)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            parser.error("generated Marauder registry is stale")
        return 0
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
